version: '3.8'

services:
  db:
    image: postgres:16
    container_name: dio_postgres
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: dio_bank
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dio-network

volumes:
  postgres_data:

networks:
  dio-network:
    driver: bridge
