"""fix foreign key user id in account 

Revision ID: ce248ba42ddd
Revises: ef6766a0f533
Create Date: 2025-09-22 20:11:27.161589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce248ba42ddd'
down_revision: Union[str, Sequence[str], None] = 'ef6766a0f533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'account', 'user', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='foreignkey')
    # ### end Alembic commands ###
